//Next JS imports
import Head from 'next/head';

//React import
import { useState, useEffect } from 'react';

//Near imports
import {
    signIn,
    signOut,
    wallet,
    viewFunction,
    callFunction,
} from '../near/near-setup';

export default function Home() {
    const [user, setUser] = useState(null);
    const [greeting, setGreeting] = useState(null);
    console.log(wallet);

    useEffect(() => {
        if (wallet.getAccountId()) {
            setUser(wallet.getAccountId());
        }
        viewFunction('get_greeting').then((result) => {
            console.log(result);
            setGreeting(result);
        });
    }, []);

    function changeGreeting(e) {
        e.preventDefault();
        const greeting = e.target.greetingInput.value;
        callFunction('set_greeting', { message: greeting }).then((result) => {
            setGreeting(greeting);
        });
    }

    return (
        <div>
            <Head>
                <title>Cryptonized</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <div className='main-div'>
                {!user ? (
                    <>
                        <h4>
                            Welcome to Cryptonized please connect your near
                            wallet
                        </h4>
                        <button
                            className='button'
                            onClick={() => {
                                signIn();
                            }}>
                            Sign In
                        </button>
                    </>
                ) : (
                    <>
                        <h4>Welcome {user}</h4>
                        <h4>
                            The contract says: {greeting}
                        </h4>
                        <form onSubmit={changeGreeting}>
                            <label>Change greeting:</label>
                            <div>
                                <input
                                    autoComplete='off'
                                    defaultValue={greeting}
                                    id='greetingInput'
                                />
                                <button>Save</button>
                            </div>
                        </form>
                        <button
                            className='button'
                            onClick={() => {
                                signOut();
                                setUser(null);
                            }}>
                            Sign out
                        </button>
                    </>
                )}
            </div>
        </div>
    );
}
